### ISSUE TITLE
Add minGap function

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#186]
A convenient function would be to measure the minimum gap between two Manifolds (good for checking that mechanisms have the proper tolerances). The signature would be: `float Manifold.MinGap(const Manifold& other, float searchLength) const`

It would always return a value between zero and `searchLength`. It would perform an intersection and if that was non-empty, it returns zero (overlapping). If not, it will collide the triangles of each mesh with the verts of the other, expanded into boxes `2*searchLength` wide, then for those collisions, calculate point-to-triangle distances. The minimum is returned.

**Comment by pca006132** [comment]
@elalish I updated the GSoC description to calculate triangle-to-triangle distance, because it is different from point-to-triangle distance. Consider two triangles where a pair of edges touch each other, but on two orthogonal planes. The point-to-triangle distance from any vertex to the opposite triangle is non-zero, but the triangle-to-triangle distance is zero.

**Comment by elalish** [comment]
Good call, thanks!

**Comment by elalish** [comment]
Added by #765
