### ISSUE TITLE
ManifoldCAD doesn't work on Firefox before 111

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#328]
https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

The worker `type: 'module'` is only recently implemented (111 is not yet released), not sure if we want this on the website as some users may still use older versions of firefox in the near future.

**Comment by elalish** [comment]
Wow, that bug was opened 7 years ago. Man, when Safari implements something first, you know you've really gotten behind.

I haven't really been worrying too much about cross-browser testing, but it's not a bad idea. Still, I'm not sure how ugly the work around for this will be. I'm tempted to just not worry about it - maybe put up a message if their browser is an unsupported version. What do you think?

**Comment by pca006132** [comment]
Yeah I don't usually worry about cross-browser testing either (I used to even test IE, but that was years ago), but the problem is that my main driver is firefox :P

Why do we have to use modules though? I think if they allowed this bug to stay opened for so long, this should be something that can be worked around easily?

**Comment by elalish** [comment]
Yeah, if it's easy to work around, let's do that. But after that ES6 module update, I really like modules a lot better - the code is nice and clean.

**Comment by elalish** [comment]
Huh, I just tried this with Firefox 111 and it's still failing with `import declarations may only appear at top level of a module` in `worker.js`. Maybe they didn't fix it completely?

**Comment by elalish** [comment]
Excellent, I just tried it and it does indeed work!

**Comment by pca006132** [comment]
I guess we can consider this as won't fix.
