### ISSUE TITLE
vertProperties behavior

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#536]
1. We should definitely document them better.
2. Should we interpolate them according to barycentric coordinate after subdivide? It seems that we forgot to implement it. https://github.com/elalish/manifold/blob/1514c151840356398a08c798fd630caeaea38c7f/src/manifold/src/smoothing.cpp#L458-L472
3. Should the decimator update copy vertex properties after duplicating the vertices? https://github.com/elalish/manifold/blob/1514c151840356398a08c798fd630caeaea38c7f/src/manifold/src/edge_op.cpp#L324-L342

**Comment by elalish** [comment]
Ah yes, indeed I haven't gotten around to 2 yet. There's a bunch of stuff I want to do to improve smoothing as well.

For 3, no it should not copy the properties because they're identical. Better to reference them and keep the memory down. I don't think we make any assumptions about how verts and property verts relate to each other. 

Agreed, regarding the need for better docs.

**Comment by pca006132** [comment]
oh ok, for 3 I think I mixed up the MeshGL interface and our internal representation a bit, I thought we have properties for each vertex.

**Comment by elalish** [comment]
2 is fixed by #741
