### ISSUE TITLE
Large meshes result in SparseIndicie too large error - Python 

### ISSUE THREAD

**Issue by drlukeparry** [elalish/manifold#720]
Using the Python bindings of the manifold library in-conjunction with the trimesh Python library,  there is the following error when working with extremely large meshes (+200mb)

`IndexError: SparseIndices too large`

This is encountered after conversion to mesh following the boolean operation.

**Comment by pca006132** [comment]
Yeah this is because we use 32 bit integers for indices, which will cause issues when meshes are large. I thought about converting these indices to 64 bit integers, but it is hard to push for that when no users really need that.

Maybe you can tell us more about your use case to see what we can do about it.

**Comment by drlukeparry** [comment]
Thank your for responding to my query.

Generally in the field of work in 3D Printing/Additive Manufacturing, we often deal with merging large complex meshes (e.g. TPMS / lattice structures) and merging these with other geometries. These can have mesh sizes into the Gb in some extreme instances that cannot be solved through mesh decimation. Otherwise, we have to go to implicit signed distance  fields which for mechanical engineering applications are unsatisfactory due to their smoothening effect, that do not match the original BRep in CAD.

If we can solve this, I am confident that it will have a very positive impact in the area of 3D printing community. 

Thank you for your consideration,
Luke

**Comment by elalish** [comment]
Thanks! Would you mind sharing an image or maybe zoom video so we can see what kind of mesh you're talking about?

**Comment by trlsmax** [comment]
I got the same error when I do some crazy thing in OpenSCAD with manifold enabled.
```
$fn = 20;
translate([0, 0, 5000])
difference() {
    translate([0, 0, -5000])
        cylinder(h = 10, d = 512, center = true);
    for (y = [0:1.6:400]) {
        for (x = [0:0.8:400]) {
            rotate([atan(y / 5000) * 180 / 3.1415926, atan(x / 5000) * 180 / 3.1415926, 0])
                cylinder(h = 12200, d = 0.8, center = true);
            rotate([atan(y / 5000) * 180 / 3.1415926, atan(-x / 5000) * 180 / 3.1415926, 0])
                cylinder(h = 12200, d = 0.8, center = true);
            rotate([atan(-y / 5000) * 180 / 3.1415926, atan(x / 5000) * 180 / 3.1415926, 0])
                cylinder(h = 12200, d = 0.8, center = true);
            rotate([atan(-y / 5000) * 180 / 3.1415926, atan(-x / 5000) * 180 / 3.1415926, 0])
                cylinder(h = 12200, d = 0.8, center = true);
        }
    }
}
```

**Comment by elalish** [comment]
Oh, I see now - the sparse indices can be much larger than the actual number of verts, since these faces are big enough to totally defeat the BVH, so we're really getting an `O(n^2)` pairs list, because it's not really sparse. So we probably don't need to update all our internal indices from 32 to 64 bit, but we *do* need to update the `SparseIndices` specifically to 64 bit. That seems like a more reasonable change.
