### ISSUE TITLE
Another Zebra Triangulation issue

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#849]
While #832 Fixes the zebra issue from #831, a similar issue happens when using Manifold-v2.5.1 if I increase resolution:
```
$fn=64;
text(text="R",font="naturePro",size=5);
```

![out](https://github.com/elalish/manifold/assets/186094/8570a3a6-4daf-4fbc-a711-5feb3ef43731)

[zebra2.cc.zip](https://github.com/user-attachments/files/15859356/zebra2.cc.zip)

**Comment by elalish** [comment]
I don't know about increased resolution (seems pretty similar) but the big difference is this polygon is already keyholed - it's not a set of outer polygons and holes. I'd highly recommend people avoid doing the keyholing step themselves, since 1) we do it for you, 2) it's really hard to do reliably, and 3) we have more information to work with when we do it inside our triangulator. This just creates degenerate geometry that doesn't need to be there. 

Anyway, that said, I'll still try to fix this.

**Comment by kintel** [comment]
Could the keyholing have come from Manifold in this case? The original polygon is just a straight-up font outline, but I don't have that polygon in Manifold test format. I can try to export an SVG if that's helpful.

**Comment by elalish** [comment]
Well, it shouldn't. Presumably you used the same process to dump the error case as for your first zebra, right? But that one was not keyholed, so I'd assume something changed upstream.

**Comment by elalish** [comment]
It's pretty easy to check - just see if there are ~180 contours or ~6 before you call into Manifold.

**Comment by kintel** [comment]
It's possible I messed up setting some parameters. Trying again with 
MANIFOLD_DEBUG enabled and this just before calling the Triangulate() function:
```
  manifold::PolygonParams().intermediateChecks = true;
  manifold::PolygonParams().processOverlaps = false;
```

[manifold-issue-849.txt.zip](https://github.com/user-attachments/files/15934588/manifold-issue-849.txt.zip)

**Comment by elalish** [comment]
That's much better, thanks! I'm guessing you grabbed a higher-up portion of our verbose output before - an easy mistake to make with hundreds of thousands of lines of spew.
