### ISSUE TITLE
Debug MSVC build error

### ISSUE THREAD

**Issue by starseeker** [elalish/manifold#862]
Has anyone see a compile error similar to the following?

```
[1/24] Building CXX object src\polygon\CMakeFiles\polygon.dir\src\polygon.cpp.obj
FAILED: src/polygon/CMakeFiles/polygon.dir/src/polygon.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\cl.exe  /nologo /TP -Dpolygon_EXPORTS -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\polygon\include -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\utilities\include -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\utilities\..\third_party\glm -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\utilities\..\third_party\thrust -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\utilities\..\third_party\thrust\dependencies\libcudacxx\include -ID:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\collider\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /DNOMINMAX /bigobj -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP -DMANIFOLD_EXCEPTIONS=1 /showIncludes /Fosrc\polygon\CMakeFiles\polygon.dir\src\polygon.cpp.obj /Fdsrc\polygon\CMakeFiles\polygon.dir\ /FS -c D:\a\bext\bext\build\manifold\MANIFOLD_BLD-prefix\src\MANIFOLD_BLD\src\polygon\src\polygon.cpp
src\utilities\include\vec.h(236): error C2607: static assertion failed
src\utilities\include\vec.h(236): note: the template instantiation context (the oldest one first) is
src\polygon\src\polygon.cpp(306): note: see reference to class template instantiation 'manifold::Vec<`anonymous-namespace'::EarClip::VertItr>' being compiled
```

**Comment by pca006132** [comment]
We should not have `Vec<VertItr>`?

**Comment by starseeker** [comment]
It looks like it's specific to Debug building on Windows, so perhaps the CI tests should have a Debug MSVC build added?  It's one of the standard BRL-CAD build configurations, so there if nothing else we'll keep running into Debug-only issues...

**Comment by elalish** [comment]
Yeah, maybe just a debug build on the CI - as I recall, running the tests in debug mode is way too slow. 

I love how after writing C++ for this long I haven't got the slightest inkling as to why `Vec<VertItr>` would be problematic...

**Comment by pca006132** [comment]
Oh it is simple, I am lazy, and I did not write a proper deallocation for data types with non-trivial destructor for our vec. The `static_assert` is there to catch this issue and avoid using our vec for non-trivial things. I should probably just implement the proper (TM) thing.

**Comment by pca006132** [comment]
Looking at it, a proper implementation is not hard, but it requires quite a lot of code duplication due to stupid C++ partial specialization and SFINAE details. We need to use `uninitialized_copy`, `uninitialized_fill` when we initialize or copy buffers, use `destroy` for deallocation, and all of this should only be compiled when `T` has non-trivial destructor to avoid overhead. I don't think it will be worth-it. Basically, that kind of becomes C++ `vector` (and no, you cannot directly write to uninitialized data when dealing with things with non-trivial destructor, so we cannot allow users to initialize a non-empty vector with uninitialized data when it is the case...).

Actually, a similar tradeoff is there for our pstl alternative implementation. Writing a fully compliant implementation will take more code with minimal return in our case, and I don't think it is worth-it. Just make sure things will not silently go wrong is probably good enough for us.

**Comment by starseeker** [comment]
So... does that mean Debug won't be a supported build configuration?

**Comment by pca006132** [comment]
No. We will fix this, just replace that with a normal vector.

**Comment by Osyotr** [comment]
> I love how after writing C++ for this long I haven't got the slightest inkling as to why `Vec<VertItr>` would be problematic...

Probably because Vert is incomplete at the time of usage.
